# flake8: noqa

"""
    nhentai api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from nhentai-api.api_client import ApiClient

# import Configuration
from nhentai-api.configuration import Configuration

# import exceptions
from nhentai-api.exceptions import OpenApiException
from nhentai-api.exceptions import ApiAttributeError
from nhentai-api.exceptions import ApiTypeError
from nhentai-api.exceptions import ApiValueError
from nhentai-api.exceptions import ApiKeyError
from nhentai-api.exceptions import ApiException
