"""
    nhentai api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nhentai-api
from nhentai-api.model.image import Image
globals()['Image'] = Image
from nhentai-api.model.gallery_images import GalleryImages


class TestGalleryImages(unittest.TestCase):
    """GalleryImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGalleryImages(self):
        """Test GalleryImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GalleryImages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
