"""
    nhentai api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nhentai_api
from nhentai_api.model.gallery_images import GalleryImages
from nhentai_api.model.tag import Tag
globals()['GalleryImages'] = GalleryImages
globals()['Tag'] = Tag
from nhentai_api.model.gallery import Gallery


class TestGallery(unittest.TestCase):
    """Gallery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGallery(self):
        """Test Gallery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Gallery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
