"""
    nhentai api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import nhentai_api
from nhentai_api.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_galleries_id_get(self):
        """Test case for api_galleries_id_get

        """
        pass

    def test_api_galleries_search_get(self):
        """Test case for api_galleries_search_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
