"""
    nhentai api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nhentai_api
from nhentai_api.model.sort_mode import SortMode


class TestSortMode(unittest.TestCase):
    """SortMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortMode(self):
        """Test SortMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SortMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
